### ISSUE TITLE
[v3] gdrive.files.list doesnt allow pageSize > 100

### ISSUE THREAD

**Issue by yawhide** [google/google-api-nodejs-client#722] opened 2017-03-29 21:47 UTC
```
> gdrive.files.list({
        auth: client,
        userId: accountId,
        pageToken: nextPageToken,
        pageSize: 200, // tried 1000 as well as the documentation says pageSize can be within range of [1,1000]
        // orderBy: 'modifiedTime', // tried this option as well to see if it helped... it didnt
      }, function (err, result) {
        console.log(result.files.length)
})

100
```

my account has thousands of files, i actually had this function in a recursive function where if there was a `nextPageToken` i would call gdrive.files.list again. every time it would only return between [0, 100]. 

here is a reference to the gdrive v3 api https://developers.google.com/drive/v3/reference/files/list
`pageSize	integer	The maximum number of files to return per page. Acceptable values are 1 to 1000, inclusive. (Default: 100)`

is there some hidden condition to be able to get more than 100 files in a single api call?

Thanks!

**Comment by ace-n** [comment] 2017-04-03 20:18
I tried this using the API explorer on the side of the page you linked, and I couldn't reproduce the error. (Does that also have the same problem for you?)

Also, is it possible that there are only 100 files that match your query? (It looks like team drive items are not included by default.)

**Comment by yawhide** [comment] 2017-04-03 21:16
i definitely have more than 1000 files in my account. I did try the api explorer and it is indeed returning `pageSize` number of files.

![image](https://cloud.githubusercontent.com/assets/5014112/24632066/a7ebc4e8-1877-11e7-92a3-9c61840c20b7.png)

![image](https://cloud.githubusercontent.com/assets/5014112/24632118/d580d93e-1877-11e7-98bb-8baf266f8b81.png)

![image](https://cloud.githubusercontent.com/assets/5014112/24632122/d979e0ee-1877-11e7-9e15-d302fc968dbb.png)

**Comment by ace-n** [comment] 2017-04-04 20:55
Another question - what happens when you set `pageSize` to 50?

(If you get 50 results, then it's likely the library's fault. If you still get 100, I'd have to take a closer look at your code.)

**Comment by yawhide** [comment] 2017-04-04 20:59
@ace-n  thanks for responding.
![screen shot 2017-04-04 at 1 58 33 pm](https://cloud.githubusercontent.com/assets/5014112/24678306/dc0791fe-193e-11e7-977b-90856db332d0.png)

![screen shot 2017-04-04 at 1 58 27 pm](https://cloud.githubusercontent.com/assets/5014112/24678305/dbf65bbe-193e-11e7-951a-90425cc35bf1.png)

**Comment by leanderlee** [comment] 2017-12-24 00:36
Apparently this only happens if `files(permissions)` is added to the field string.

**Comment by leanderlee** [comment] 2017-12-24 00:40
This seems to be a bug with the google drive API and not with the nodejs client, since it happens on the API explorer as well.

**Comment by JustinBeckwith** [comment] 2018-03-08 05:41
If this is present in the API, there's not a lot we can do here :(  Closing this out for now.

**Closed by JustinBeckwith** 2018-03-08 05:41 UTC
Labels: Priority: P2+, Status: Acknowledged, Type: Question

**Comment by vishal847** [comment] 2018-10-26 11:34
It might help you https://stackoverflow.com/questions/42592125/list-request-page-size-being-ignored
