### ISSUE TITLE
Change in the require  - var {google} = require('go.... vs var google = requi...

### ISSUE THREAD

**Issue by mreggiardo** [google/google-api-nodejs-client#1025] opened 2018-02-26 17:53 UTC
I copy and try to run the example for sheet api in the API site
https://developers.google.com/sheets/api/quickstart/nodejs

After battling some timei found out that the require was changed

you use 
**var {google} = require('googleapis');**
Instead 
**var google = require('googleapis');**

The second one gives an error of **typeError: google.sheets is not a function**

There is very few documetation in other places.. please fix the examples and documentation. 

regards

**Comment by JustinBeckwith** [comment] 2018-02-26 18:19
Duplicate of #952

**Closed by JustinBeckwith** 2018-02-26 18:19 UTC
