### ISSUE TITLE
try to run list with search using version 14.1.0

### ISSUE THREAD

**Issue by drorzp** [google/google-api-nodejs-client#665] opened 2016-10-26 19:14 UTC
I am trying to search for a file/files using the files.list and 
try to look for a specific property .

I keep on getting 'invalid query 400'
any idea what is the problem?

```js
 drive.files.list({
                  q: "properties has { key='opportunityId' and value='12345'}",
                    auth: authClient
                    }, function(err, res) {
                        if (err) callback(err, null);
                        else callback(null, res.items);
                    });
                }
```
when i run the above i get  invalid query
all works fine for the one below:
```js
  drive.files.list({
                  q: "title='a33'",
                    auth: authClient
                    }, function(err, res) {
                        if (err) callback(err, null);
                        else callback(null, res.items);
                    });
```
all works  any idea ?

**Comment by jmdobry** [comment] 2016-12-28 22:31
I can't reproduce your error. I passed `q: "properties has { key='opportunityId' and value='12345'}"` to `drive.files.list` and it worked fine. Here is the code I used: https://github.com/google/google-api-nodejs-client/pull/690/files#diff-cdcd50a2dd6c38e22222ea1a9a698fd9

**Comment by lukesneeringer** [comment] 2017-04-12 21:04
Hi @drorzp,
It has been awhile since we last heard from  you, so I am going to close this ticket. Please feel free to reopen with more information if you wish.

**Closed by lukesneeringer** 2017-04-12 21:04 UTC
