### ISSUE TITLE
Module not found: Error: Can't resolve './types/other' 

### ISSUE THREAD

**Issue by arjunvegda** [google/google-api-nodejs-client#1226] opened 2018-07-05 01:45 UTC
Hello folks,

I am very new to Dialogflow and have been fiddling around to make a chatbot. 
I was able to successfully hook up the `googleapis` module and everything works fine on locally. 

Package versions
`npm: 6.1.0`
`node: 8.11.1`
`googleapis: 32.0.0`

**Goal**:
To be able to create intents dynamically and push them to Dialogflow. Here is the code snippet

`postNewData.ts` 
```ts
import { getIntent } from './intents';
const { google } = require('googleapis');

export async function postDataToDialogFlow() {
  const client = await google.auth.getClient({
    keyFile: process.env.GOOGLE_APPLICATION_CREDENTIALS,
    scopes: 'https://www.googleapis.com/auth/cloud-platform',
  });

  const dialogflow = google.dialogflow({
    version: 'v2',
    auth: client,
  });

  dialogflow.projects.agent.intents
  .create({
    parent: `projects/${process.env.DIALOGFLOW_PROJECT_ID}/agent`,
    resource: getIntent(),
  })
  .catch(err => {
    console.error(`Error caught while creating an intent on Dialogflow: ` + err);
  });
}

```

**Problem**

I was able to successfully push the new intent to Dialogflow. The problem occurs when I run <br/> `npm run build` which executes `node --max-old-space-size=4096 ./node_modules/webpack/bin/webpack.js --display-error-detail --mode=production`<br/>
and throws these two errors which ends up failing the circleci build.

I did try to debug further but no luck so far. I apologize if the issue has been discussed earlier and failed to catch my eyes.

```
ERROR in ./node_modules/gtoken/node_modules/mime/index.js
Module not found: Error: Can't resolve './types/other' in '/Users/arjun/projects/bot/node_modules/gtoken/node_modules/mime'
 @ ./node_modules/gtoken/node_modules/mime/index.js 4:55-79
 @ ./node_modules/gtoken/build/src/index.js
 @ ./node_modules/google-auth-library/build/src/auth/jwtclient.js
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/shared/src/discovery.js
 @ ./node_modules/googleapis/build/src/shared/src/index.js
 @ ./node_modules/googleapis/build/src/apis/youtubereporting/v1.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/natural-language-processing/queries/postNewData.ts
 @ ./src/natural-language-processing/queries/index.ts
 @ ./src/natural-language-processing/index.ts
 @ ./src/server.ts
```
```
ERROR in ./node_modules/gtoken/node_modules/mime/index.js
Module not found: Error: Can't resolve './types/standard' in '/Users/arjun/projects/bot/node_modules/gtoken/node_modules/mime'
 @ ./node_modules/gtoken/node_modules/mime/index.js 4:26-53
 @ ./node_modules/gtoken/build/src/index.js
 @ ./node_modules/google-auth-library/build/src/auth/jwtclient.js
 @ ./node_modules/google-auth-library/build/src/index.js
 @ ./node_modules/googleapis/build/src/shared/src/discovery.js
 @ ./node_modules/googleapis/build/src/shared/src/index.js
 @ ./node_modules/googleapis/build/src/apis/youtubereporting/v1.js
 @ ./node_modules/googleapis/build/src/index.js
 @ ./src/natural-language-processing/queries/postNewData.ts
 @ ./src/natural-language-processing/queries/index.ts
 @ ./src/natural-language-processing/index.ts
 @ ./src/server.ts
```

I'd appreciate any input on this. 

Thank you 👍

**Comment by JustinBeckwith** [comment] 2018-07-05 02:14
Greetings!  This library ain't exactly webpackable today, sadly.  The problem is the dependency on Google auth library (a pretty important dependency).   The good news is that we have made some good progress :). 

https://github.com/google/google-auth-library-nodejs/pull/371

I suggest following that issue for updates.

**Comment by arjunvegda** [comment] 2018-07-05 14:21
Oh no :( Okay. Thank you for sharing the link. 👍

**Comment by JustinBeckwith** [comment] 2018-08-12 19:47
Also added an item to track here: 
https://github.com/google/google-api-nodejs-client/issues/1286

I'm going to close this out for now, but we should have news here soon 🤞

**Closed by JustinBeckwith** 2018-08-12 19:47 UTC
Labels: :rotating_light:, triage me
