### ISSUE TITLE
oauth2 - v3

### ISSUE THREAD

**Issue by eelsweb** [google/google-api-nodejs-client#490] opened 2015-11-16 03:44 UTC
There seems to be no v3 for the oauth2 apis. Is there a way to access this - 

https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=XYZ123

**Comment by eelsweb** [comment] 2015-11-16 03:47
i could try to create this particular endpoint if needed.

**Comment by jmdobry** [comment] 2016-03-04 05:11
Currently, private APIs cannot be accessed in google-api-nodejs-client v2.1.7. See #487. If you've been given access to a discovery doc, then you can clone this repository and generate the client for the API to which you've been given access. If it's a JSON file then #488 may help you out. If it's an actual discovery url, then it should be easy for `lib/generate.js` to generate the client for you.

This isn't easy to do now, but we're working on it.

**Comment by jmdobry** [comment] 2016-03-04 05:12
Duplicate of #487 and #489.

**Closed by jmdobry** 2016-03-04 05:12 UTC
Labels: duplicate
